services:
  - type: web
    name: tire-backend
    env: docker
    dockerfilePath: ./Dockerfile.prod
    plan: free
    region: frankfurt
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: tire-db
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: tire-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr
databases:
  - name: tire-db
    plan: free
    region: frankfurt
